---
title: "R Notebook"
output: html_notebook
---

Introduction to the tydiverse

```{r}
library(gapminder)
library(dplyr)
gapminder

```
/-------FILTERING---------------------/
```{r}
gapminder %>%                         
  filter(year==1957)
```
/------------------ARRGANE-----------------------------/

```{r}

gapminder %>%
  arrange(lifeExp)

gapminder %>%
  arrange(desc(lifeExp))
```
/------------FILTER AND ARRNGE-------------------/
```{r}
gapminder %>%
  filter(year==1957) %>%
  arrange(desc(pop))

```
/-------------------THE VERB MUTATE-------------------/
```{r}
gapminder %>%
mutate(lifeExp=12 * lifeExp)
gapminder %>%
  mutate(lifeExpMonths=12*lifeExp)
```
/-----------------Combining filter, mutate and arrane------------------------/
```{r}
gapminder %>%
  filter(year==2007) %>%
  mutate(lifeExpMonths=12*lifeExp) %>%
  arrange(desc(lifeExpMonths))

```
```{r}
library(ggplot2)
gapminder_1952 <-gapminder %>%
  filter(year==1952)
gapminder_1952
ggplot (gapminder_1952,aes(x=pop,y=gdpPercap)) +
geom_point()  

```
/--------------LOG SCALINg------------------------/
```{r}

ggplot(gapminder_1952,aes(x=pop,y=gdpPercap))+
  geom_point()+
  scale_x_log10()+
  scale_y_log10()

```
```{r}
ggplot(gapminder_1952,aes(x=pop,y=lifeExp,color=continent)) +
  geom_point()+
  scale_x_log10()
```
Finalizacion  3/07/2021
```{r}
ggplot(gapminder_1952,aes(x=pop,y=lifeExp,color=continent,size=gdpPercap)) +
  geom_point()+
  scale_x_log10()

```
----INICIO 10/07/2021
--------------------------------
```{r}
gapminder_1952


ggplot(gapminder_1952,aes(x=pop,y=lifeExp))+
  geom_point() +
  scale_x_log10() +
facet_wrap(~ continent)


ggplot(gapminder,aes(x=gdpPercap,y=lifeExp))+
  geom_point() +
  scale_x_log10() +
facet_wrap(~ year)
```

